### ISSUE TITLE
Docker build failing on Linux (Xubuntu 16.04)

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/earth-analytics-python-env#10]
The instructions do not say to create a new directory called earth-analytics-binder, but in order to cd to it, I created it and copied environment.yml and Dockerfile into this new folder. 

When running the provided command (docker build -t earthlab/earth-analytics .), the build seems to fail when trying to download repodata.json.bz2 file from https://repo.anaconda.com/pkgs/main/linux-64/.  I checked that the file exists, but it appears to have been updated today and may have an error.

**Comment by lwasser** [comment]
oh @jlpalomino  this is another update. the repo used to be called earth-analytics-binder. so if you cloned the repo you'd have that dir. just last week - we renamed the repo to `earth-analytics-python-env` so please update the instructions to cd to that dir which a user will have after cloning the repo!

**Comment by lwasser** [comment]
also it's interesting you needed the token and i didn't. can we try this again together so i can see please? also i think we renamed the docker image earth-analytics-python so there may be a few dated things here in the documentation. let's figure it out. Also @mbjoseph  may be able to help test on his linux machine.

**Comment by lwasser** [comment]
when we sort it out you can submit a pr to update the docs!! i've assigned this to you.

**Comment by mbjoseph** [comment]
Bah. As @jlpalomino noticed and @lwasser points out, out the docs are out of date :frowning_face: 

The instructions to build the image should be: 

```bash
cd earth-analytics-python-env
docker build -t earthlab/earth-analytics-python-env .
```

I can confirm that the URL generated substitutes the container ID for localhost. I have no idea why this is. But if we can fix it, that would be great. I posted something on Twitter tagging the Jupyter team and Docker but all I got was crickets. We could probably open an issue here to get help: https://github.com/jupyter/docker-stacks

We can always check the build status on Docker Hub here if we need to: https://hub.docker.com/r/earthlab/earth-analytics-python-env/builds/

We also might want to add these badges to the README to point to the automated build and get the status: 

[![Docker Automated build](https://img.shields.io/docker/automated/earthlab/earth-analytics-python-env.svg)](https://hub.docker.com/r/earthlab/earth-analytics-python-env/)

^ in markdown is `[![Docker Automated build](https://img.shields.io/docker/automated/earthlab/earth-analytics-python-env.svg)](https://hub.docker.com/r/earthlab/earth-analytics-python-env/)`


[![Docker Build Status](https://img.shields.io/docker/build/earthlab/earth-analytics-python-env.svg)](https://hub.docker.com/r/earthlab/earth-analytics-python-env/)

^ is `[![Docker Build Status](https://img.shields.io/docker/build/earthlab/earth-analytics-python-env.svg)](https://hub.docker.com/r/earthlab/earth-analytics-python-env/)`

**Comment by lwasser** [comment]
🐐 baaaaaaaaah 
thanks @mbjoseph  i can ask Tim about this too :) i'm curious about how that all works and sometimes a key is really not necessary anyway. @jlpalomino let's update, add the badges and such as max suggests above! it will be a good exercise for you to get used to our GH workflow :) i find each place i work is slightly different so good to practice for everyone! :)

**Comment by jlpalomino** [comment]
To resolve this issue about the install itself, I will create a pull request to update the README.md, per the response by Max.

I'll create new issues for the URL generated by Docker (i.e. URL generated substitutes the container ID for localhost) in both earthlab/earth-analytics-python-env and jupyter/docker-stacks.

**Comment by jlpalomino** [comment]
No need for a new issue on jupyter/docker-stacks. I found an existing issue on jupyter/docker-stacks (https://github.com/jupyter/docker-stacks/issues/642) that addresses this issue with the URL generated by Docker (i.e. URL generated substitutes the container ID for localhost), and it works. 

docker run --hostname localhost -it -p 8888:8888 earthlab/earth-analytics-python-env
 
I'll create a new issue and pull request to update the README.md to update the command.
