### ISSUE TITLE
Update README for Windows users

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earth-analytics-python-env#22]
Currently we suggest `source activate my-env` to activate the environment, but Windows users should just do `activate my-env`.

**Comment by lwasser** [comment]
ahhhh sure @mbjoseph do you want to submit a PR on this to update the readme? thank you for catching it!!!

**Comment by lwasser** [comment]
i'm reopening this issue so we can also chat here

**Comment by lwasser** [comment]
this was fixed - closing the issue!!
