### ISSUE TITLE
Investigate making the docker image smaller

### ISSUE THREAD

**Issue by betatim** [earthlab/earth-analytics-python-env#23]
Investigate options for making the built docker image smaller.

**Comment by betatim** [comment]
Spent a bit of time looking into how big this image is and ways to make the image smaller. The motivation for this is that pulling a large image like this takes long which means when people login to the earthlabhub and are unlucky enough to end up on a new virtual machine that doesn't already have the image they have to wait a few minutes for the image to be pulled.

This image is based on [`jupyter/scipy-notebook` from the docker-stacks repo](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-scipy-notebook). They have some nice badges to tell you how big the image is: https://microbadger.com/images/jupyter/scipy-notebook and then our image: https://microbadger.com/images/earthlab/earth-analytics-python-env/

This makes me think our image is about 2.1G large, 600MB bigger than the jupyter/scipy-notebook (at 1.5GB).

When I pull both images to my laptop and look at `docker images` I see:
```
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
earthlab/earth-analytics-python-env   266950b             6c8c4ad8d561        47 hours ago        6.47GB
jupyter/scipy-notebook                177037d09156        07f647bee0ec        2 days ago          4.58GB
```

My biggest confusion is about the fact that the size shown here seems to have nothing to do with what microbadger shows :-/

**Comment by lwasser** [comment]
this is beyond me! @mbjoseph  just curious. do you know anything about optimizing docker image size? ours is large and we just want to make it smaller if possible as it's a slow point in our hub deployment. i could also ping the twitterverse!

**Comment by mbjoseph** [comment]
I think the short answer is to make sure that the only things installed in the image are the things that we need. For example, do we need to have everything that is pre-installed in the scipy-notebook image? The source code for it is here: https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile

**Comment by betatim** [comment]
Agreed. But also no idea what is really needed :-/

Might investigate what minimal-notebook + `environment.yml` from this repo gives in terms of size.

**Comment by lwasser** [comment]
ok! also i notice there that there are packages like seaborn that i may install that are already in scipy... i'm open to adjusting as needed here! thank you both

**Comment by lwasser** [comment]
we've worked with the conda forge folks to make this build much smaller i think!! i'll close this for now as it's been stale for a while. thank you all!
