### ISSUE TITLE
Pin package versions in our environment

### ISSUE THREAD

**Issue by lwasser** [earthlab/earth-analytics-python-env#32]
Currently when i make an update, i'm just adding new packages without considering versions. This is NOT a good idea as sometimes things update in a way that breaks other packages.

After this course is over, experiment with pinning each package version so that we have a set of known packages that work together at x version.

@mbjoseph -- do you have any thoughts on how i could setup testing (or could you help me??) so that we test that all packages import with a new version of this envt? I am not even sure how to start but i'd sure love to get a message prior to the students encountering errors as a part of the docker build or even BEFORE the docker build.

**Comment by mbjoseph** [comment]
Heya @lwasser - I think we should be able to check that packages import without raising errors using Travis or some other CI. 

Was the issue in this case that the Docker image built successfully, but some package(s) could not be imported?

**Comment by lwasser** [comment]
yea. In this case, the issue is a gdal / libgdal / kealib issue that caused rasterio to not load properly. this would impct a geopandas import too. I think i know the fix now. BUT boy would it be nice to submit a pr and test BEFORE launching the fix you know and testing it that way?? I know i could build locally too but ideally travis could test importing all packages.

down the road i'd like to test notebook builds or atleast code. i suppose we could do that too right just like we do for earthpy?? 

Can we run test on different operating systems by chance with travis or circleci? just curious. i think implementing testing imports is a great start. but it would be really nice if i could build a bunch of tests like for earthpy and run them on mac, linux and windows. i know it's a lot just wondering what is possible.

**Comment by mbjoseph** [comment]
Cool - thanks for the extra information! I agree it would be nice for Travis to at least verify that the packages can be imported. I ran into a similar thing with gdal installing without error, then raising errors upon import.

I agree that testing notebook builds would be good - maybe for example running the notebooks that are used to generate the Python material for the website and your classes? 

As far as testing on multiple platforms, I have used Appveyor to test on Windows, but have never tried to get something to be tested on linux, mac, and windows. Jenkins may be able to do this, but I'm not sure how to set it up.

**Comment by lwasser** [comment]
Ok well you know a first great step here is just to setup travis to test imports. Can we do that using  a similar setup we have in earthpy?

It doesn’t have to be in notebooks. We can just have scripts ☺ that would be super awesome as a start.

PS – the issue with GDAL, libgdal and libkea (kealib is the actualy package that throws an error) libkea is often what the error references. If you install one on conda forge and the other(s) on pip it fails. So in our env I need to add kealib to the installs under libgdal which I updated last time in the env when this happened. It’s a dependency so not something you’d think to be explicit about. Or atleast not something I thought to be explicit about!! Last time it took me weeks to troubleshoot. Now I know what the issue is. ☺

**Comment by mbjoseph** [comment]
We can probably use a similar approach, but the difference is that for earthpy, we are running a setup.py script, and here, we might want to run a different script like `import_all.py` that is just a bunch of import statements. I see two potential options for how to make this work:

1. Try to be fancy about automating the generation of the `import_all.py` script. I'm not sure how to do this, since the package names for install commands are not always the same as the package names for import commands, e.g., `conda install scikit-image` vs. `import skimage`. Maybe you have some ideas for how we could do this though?

2. Edit the `import_all.py` script manually, and try to remember to always add any new packages that show up in the `environment.yml` file, if applicable. This seems error prone though, because we might forget to update `import_all.py`. 

@lwasser do you have any other ideas for how we could check that everything actually imports?

**Comment by joemcglinchy** [comment]
what about `modulefinder`? https://docs.python.org/3.6/library/modulefinder.html

**Comment by lwasser** [comment]
let's see... in @joemcglinchy example above we'd want to export notebooks to .py script and generate a list of modules then run them?

that could work but would be a bit of effort given we have hundreds of notebooks BUT... in the spring when we do our automated build that might be something we consider integrating into our course website infrastructure!!

I can't think of a clever way to grab package names.. but we could also curate a yaml file that perhaps is built using the envt yaml file that has a second "layer" which is the module import ??

If we add stuff to this repo will the docker file then get bigger ? just thinking about anyone that might use the docker image. i'm thinking using Joe's suggestion above we could definitely then test all of the notebooks against our less when we develop our website build. And this would just test imports. that could work nicely.

**Comment by mbjoseph** [comment]
Thanks @joemcglinchy - It looks like modulefinder finds modules imported by python scripts, which is a somewhat inverted problem (but one that we will probably run into later).

The issue that I'm struggling with is how to go from the specification of libraries in the `environment.yml` file to a python script that imports everything. 

I wonder whether a cleaner solution would be to more directly capture the connection between this environment and the teaching material. For instance, use this environment to build the lessons via CI as part of the broader effort to automate the teaching site content generation. What do you think @lwasser?

**Comment by lwasser** [comment]
HAHA... see my statement above @mbjoseph  we are on the same page :) If we did that @joemcglinchy solution could work OR maybe the CI part does happen on the lesson build.
HEre is the issue with that @mbjoseph we don't want to always rebuild all lessons. but we do want to always test this envt when i update it. know what i mean?

**Comment by mbjoseph** [comment]
> HEre is the issue with that @mbjoseph we don't want to always rebuild all lessons. but we do want to always test this envt when i update it. know what i mean?

Yep - I hear that. I wonder whether we can set up CI to rebuild everything when the environment gets updated, but only build/rebuild changed lessons when the environment is unchanged?

**Comment by lwasser** [comment]
Sure... possibly! Some of me thinks that could be great. Some of me worries but may be unfounded worry
1. we have a lot of lessons. so a build could take a long time and each build might change lessons - example -- twitter api lessons. each time it grabs a new collection of tweets. 
2. What is something changes in the module but doesn't throw an error but plots and data munging tasks are impacted. Our lessons then change online, i don't know until someone tells me or i see it myself working on it. 

just thinking outloud here ...
Some of me wonders if we want to have a list of all modules imported in my lessons (and in the tutorials) and then build unit tests or just have a set of notebooks that run when the envt updates that aren't tied to the website... hmmmm

**Comment by lwasser** [comment]
ok wonderful. Based on our discussion today i will
1. **Pin all versions as specified in the hub right now in the yaml file:** This will avoid students inadvertently updating and upgrading to versions that break things.  It will allow me to carefully and selectively upgrade as i see fit. I think i should do this once a semester or so in between courses when there is time to test lesson updates.
2. Max has some ideas to create a CI build that tests import of each package in the envt based upon what we are using in the EA lessons and tutorials. Sure this won't address all issues but it's a fantastic start!

**Comment by betatim** [comment]
Recently learnt about an extra option for `conda env export`: `--no-builds`. If you run `conda env export -f test.yml` you get something like the following:
```yaml
name: grading-workflows
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_0
  - backcall=0.1.0=py_0
  - bleach=2.1.4=py_1
```

The `py36_0` and `py_1` things at the end of each line specify which build of the `appnope` package in version 0.1.0 is installed. This is useful if you want to get *exactly* the same things installed again later. However I find that when I export the environment on (say) OSX and then want to use it on a linux machine it is virtually guaranteed that it doesn't work because there is no build `pv36_0` for appnope 0.1.0 on windows. If you add `--no-builds` you get:
```yaml
name: grading-workflows
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - backcall=0.1.0
  - bleach=2.1.4
```
which most of the time is what I actually wanted. I want version 0.1.0 of appnope and don't care which version of the conda package it is.

**Comment by lwasser** [comment]
ahhh thank you @betatim funny... i had this thought the other day - just a question in my mind about whether that would work across platforms as i know there are different installs for different platforms just based upon different behaviors i have seen. ok great. we will use the no-builds qualfiers to JUST pin the version (which is what i want) and not the build (which is platform specific).

THANK YOU SO MUCH.

**Comment by betatim** [comment]
I think you can still end up in situations where the specific combination of packages and versions doesn't work on all platforms but that is much rarer. When it happens you can still go in and by hand loosen one of the dependencies: `appnope=0.1.0` -> `appnope=0.1.*` and the like.

**Comment by lwasser** [comment]
ok cool. yea i was reading about that. You know with that matplotlib issue version .1 was broken and version .2 was the fix. In other instances the above example is exactly what we need for things like pyproj where actually there were slightly different issues with different versions across windows vs other platforms. thank you so so much for this guidance!!

**Comment by lwasser** [comment]
closing this as i think we have a handle on version issues now and it's been open for well over a year!!
