### ISSUE TITLE
Check that packages import on Travis

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/earth-analytics-python-env#33]
It would be good to verify that the packages installed in this environment and used in lessons can be imported. Doing this in the CI build would require:

1. Fetching the lessons
2. Using modulefinder to generate a set of imported modules
3. Iterating over that set to verify that modules can be imported

If any module cannot be imported, the build is broken.

**Comment by lwasser** [comment]
yes! and just a note that it's the import that fails. when you `import modulex` or `from modulex import fun` that  breaks  sometimes even with a clean install :)

**Comment by mbjoseph** [comment]
Oh yes thanks @lwasser! I wrote "installed" but meant "imported".

**Comment by lwasser** [comment]
this also has been implemented! closing. thank you @mbjoseph i'm closing all of these old issues that we resolved ! i always forget to do this.
