### ISSUE TITLE
Updating notebooks to utilize earthpy.plot functions more often

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earth-analytics-python-env#35]
Use new functions added to earthpy through earthpy.plot to make notebooks easier. For example, in the intro to lidar raster landing page, there is a code block that looks like this:

```
# create histogram
fig, ax = plt.subplots(figsize=(10, 6))
data = diff_chm_crop.ravel()[~np.isnan(diff_chm_crop.ravel())]
ax.hist(data, bins=20, range=(-10, 10), color='purple', edgecolor='k')

# set titles & display properties
ax.set_facecolor('w')
ax.spines['left'].set_color('k')
ax.spines['bottom'].set_color('k')
ax.set(xlabel='Elevation (m)', ylabel='Frequency',
       title='Homework plot 1: \n Histogram of Pre/Post Flood CHM Difference\n post flood minus pre flood')
plt.show()
```
I am fairly certain this could be replaced with 
```
import earthpy.plot as ep
ep.hist(diff_chm_crop, bins=20, colors=["purple"], title=''Homework plot 1: \n Histogram of Pre/Post Flood CHM Difference\n post flood minus pre flood")
``` 
It may be useful not to utilize the functions so the students get used to wrestling with matplotlib fig and ax, but it would certainly be more effecient. Let me know thoughts! @lwasser

**Comment by nkorinek** [comment]
Quick update: I just realized I put this on the wrong github page, it should be over on github.com/earthlab/earth-analytics-python instead, whoops!

**Comment by lwasser** [comment]
@nkorinek just seeing this here. i will close it. it's definitely in the wrong spot!
