### ISSUE TITLE
Should nb_conda and nb_conda kernels be included in the envt and docker image image?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earth-analytics-python-env#6]
currently we have removed `nb_conda` and `nb_conda_kernels` from our conda envt.
nb conda adds a nice interface to notebooks that allows students to explore environments on their computer, update packages etc. 

https://github.com/Anaconda-Platform/nb_conda

While this is nice for teaching, i'm not clear how it interfaces in a jupyterhub environment because in that envt, presumably students don't have permissions to CHANGE their envt - correct? so i do think that exposing students to the packages and such is powerful. but can they change them in a jupyterhub implementation where nb_conda is available? i don't want that to happen. 

i'm curious if @choldgraf bu chance has any thoughts on using `nb_conda` in a jupyterhub envt in the cloud. if we remove it from the envt then students will have to install it manually.

**Comment by choldgraf** [comment]
students actually should be able to change their environment, provided that packages get installed to a user directory and not a system directory...give it a shot and see if it works! (I've never used nb_conda though)

**Comment by lwasser** [comment]
oh wait. can you do that? do they could customize their jupyterhub environment on the cloud IF it is installed in their user directory as opposed to the system root? is that what you are saying @choldgraf ? i didn't even know that was possible. i think the default anaconda install sits in the computer home directory or something but not sure in the cloud what the structure looks like??

**Comment by choldgraf** [comment]
yeah I think so - the students could run `pip install XXX` and it should work so long as you give it the flag to install to your user directory (this will install it in their local storage, which is owned by them and persists over time)

**Comment by lwasser** [comment]
ahhhhh that makes a lot of sense @choldgraf right they could do pip install -e or something like that. i get it. ok thank you!!

**Comment by lwasser** [comment]
ok - i'm going to close this issue as i did add nb_conda back to the install. thank you for the help @choldgraf 

2d82eae1820ad9dd8fef14461cc24064c5643fd5
