### ISSUE TITLE
hillshade values issue

### ISSUE THREAD

**Issue by BCNecoder** [earthlab/earth-analytics-python-env#64]
Hi there!

I got a problem in the pixel values when calculating hillshade with earthpy it rarely yields the same values than making the same operation with gdal or acrpy.
What is it due to?

**Comment by lwasser** [comment]
hi @BCNecoder !! this issue might be better addressed in the [earthpy](https://www.github.com/earthlab/earthpy) repo as this is our python environment repo!  there are many different ways to calculate a hillshade! We selected one that works but i'm guessing that gdal and arcpy use other methods. There are also settings that you can adjust within the hillshade function using parameters so you could see what the default settings are with gdal and arcpy and set those in our hillshade function. I hope that helps! the hill shade in earthpy was not intended to be a scientific output necessarily - we mostly use it for maps. however if there are algorithms that you would like to see in earthpy please feel free to open an issue over there!!

**Comment by BCNecoder** [comment]
Thank yo for your kind response.
Best
