### ISSUE TITLE
Can't create earth-analytics-python 

### ISSUE THREAD

**Issue by stager1** [earthlab/earth-analytics-python-env#69]
+ ---
+ name : Bug report
+ about: Create a report to help us improve
+ title: Issue with earth analytics python environment
+ labels : ''
+ assiganees: ''
+ 
+ ---
+
+ 
+ **Describe the issue**
+ conda env create  -f envirionment.yml fails
+ error received: 
+ ResolvePackageNotFound:
+ •	papermill
+ •	nbgrader
+
+ Desktop (please complete the following information):**
+ - OS: Windows
+ - Browser: firefox
+ - Version: 75.0 (64-bit)
+
+ <br>
+ Environment (<code>conda list</code>):
+ </details>
+
+```
+ $ conda list
+
+```
+ <details>
+
packages in environment at C:\Users\Laura\miniconda3:
Name Version Build Channel
ca-certificates 2020.1.1 0
certifi 2020.4.5.1 py37_0
cffi 1.14.0 py37h7a1dbc1_0
chardet 3.0.4 py37_1003
conda 4.8.3 py37_0
conda-package-handling 1.6.1 py37h62dcd97_0
console_shortcut 0.1.1 4
cryptography 2.9.2 py37h7a1dbc1_0
idna 2.9 py_1
menuinst 1.4.16 py37he774522_0
openssl 1.1.1g he774522_0
pip 20.0.2 py37_1
powershell_shortcut 0.0.1 3
pycosat 0.6.3 py37he774522_0
pycparser 2.20 py_0
pyopenssl 19.1.0 py37_0
pysocks 1.7.1 py37_0
python 3.7.7 h81c818b_4
pywin32 227 py37he774522_1
requests 2.23.0 py37_0
ruamel_yaml 0.15.87 py37he774522_0
setuptools 46.1.3 py37_0
six 1.14.0 py37_0
sqlite 3.31.1 h2a8f88b_1
tqdm 4.46.0 py_0
urllib3 1.25.8 py37_0
vc 14.1 h0510ff6_4
vs2015_runtime 14.16.27012 hf0eaf9b_1
wheel 0.34.2 py37_0
win_inet_pton 1.1.0 py37_0
wincertstore 0.2 py37_0
yaml 0.1.7 h896c600_2
zlib 1.2.11 h33f27b4_4
(base)
+ <br/>
+ Details about   <code>conda</code> and system ( <code>conda info</code> ):
+ <details>
+
+```
+ $ conda info
+
+```
+ </details>
 active environment : base
active env location : C:\Users\Laura\miniconda3
        shell level : 1
   user config file : C:\Users\Laura\.condarc
populated config files : C:\Users\Laura.condarc
conda version : 4.8.3
conda-build version : not installed
python version : 3.7.7.final.0
virtual packages :
base environment : C:\Users\Laura\miniconda3 (writable)
channel URLs : https://repo.anaconda.com/pkgs/main/win-32
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/free/win-32
https://repo.anaconda.com/pkgs/free/noarch
https://repo.anaconda.com/pkgs/r/win-32
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-32
https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\Users\Laura\miniconda3\pkgs
C:\Users\Laura.conda\pkgs
C:\Users\Laura\AppData\Local\conda\conda\pkgs
envs directories : C:\Users\Laura\miniconda3\envs
C:\Users\Laura.conda\envs
C:\Users\Laura\AppData\Local\conda\conda\envs
platform : win-32
user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.18362
administrator : False
netrc file : None
offline mode : False
(base)

**Comment by lwasser** [comment]
hey @stager1 you definitely do not want to mix pip and conda installs! you can totally delete nbgrader and papermill however from the envt and still run through all of our lessons so that is a safe set of things to remove.

I am not able to recreate your issue on windows 10 or mac.
 
What does this:
`conda info --envs`

return?

It may be worth trying to install the environment again. if conda info --envs shows earth-analytics-python was installed (in part i presume) you will want to [remove it ](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#removing-an-environment) first.

**Comment by stager1** [comment]
conda info returns:
$ conda info --envs  
# conda environments:
#
base                  *  C:\Users\Laura\miniconda3
myenv                    C:\Users\Laura\miniconda3\envs\myenv

(base)
 
Already tried deleting papermill and nbgraber, it doesn't install envirnoment and returns:
$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining numpy:   0%|                                                                          | 0/32 [00:00<?, ?it/s]-Examining ipython:  22%|█████
.......... and on for pages.

Tried both installing env again with papermill and nbgraber and with deleting those 2 again and same result.

Probably will try uninstalling miniconda and trying again.  Thanks for looking at it.

**Comment by stager1** [comment]
When I use miniconda 32 bit get the same errors.  miniconda 64 bit worked and I have environment installed.  Looking forward to learning more. Thanks.

**Comment by lwasser** [comment]
awesome! glad it all installed @stager1 i'll close this given it sounds like it's all working now. And good to know that the version of miniconda impacted your envt install. this actually does make sense to me!!
