### ISSUE TITLE
Issue with earth analytics python environment

### ISSUE THREAD

**Issue by dmovchan84** [earthlab/earth-analytics-python-env#79]
**Describe the issue**
I can't install the Earth Analytics Python Conda Environment. When I try to run `conda env create -f environment.yml` code in the Terminal, I get the following output:

> Solving environment: failed
> 
> ResolvePackageNotFound:
>   - nbgrader
>

**Desktop:**
 - OS: Windows 7, 32
 - Browser Chrome
 - Version 87.0.4280.66
 - Conda version 4.8.3
 - Python version 3.8.3.final.0

**Comment by lwasser** [comment]
hi @dmovchan84 we can look into this. in the meantime I suggest that you comment out nbgrader from the build as that tool is largely used for our course grading and you may not need it. you can just add a `#` sign to the line in the yaml file if you want to do that so it looks like this:

`#-nbgrader`

or delete the line altogether. something must be wrong with the nbgrader build right now.

**Comment by dmovchan84** [comment]
Thank you @lwasser for your reply. Following the recommendation, I have commented out nbgrader from the build and now code is running. But as output, now I have a huge list of package conflicts.
![conflicts](https://user-images.githubusercontent.com/74907276/100069556-91df1400-2e41-11eb-88f8-24878d203286.jpg)

**Comment by lwasser** [comment]
can you please provide the output of `conda info` ? this may not be an issue that i can resolve as  it could be a conda issue but let's see...  

other questions
* are you running anaconda or miniconda? We suggest using miniconda
* Is you conda install 32 or 64 bit?
* Are you running 32 or 64 bit windows?

I'm wondering if you have a 32 bit installation but are on a 64 bit machine.

**Comment by dmovchan84** [comment]
here is my `conda info`

![conda-info](https://user-images.githubusercontent.com/74907276/100222186-6849e980-2f22-11eb-88a3-0581f63d5e37.jpg)

my windows and conda are 32 bit.

**Comment by dmovchan84** [comment]
I have just tried it on another machine with a different system. Everything is working. So, I close this issue as unsolved.

**Comment by lwasser** [comment]
sounds good! i really do think it's because of the 32 bit windows that you are running. that is what  i see in the screenshot above. the environment will not work properly in that envt as of now.
