### ISSUE TITLE
can earth-analytics be renamed --> earth-analytics-python?

### ISSUE THREAD

**Issue by lwasser** [earthlab/earth-analytics-python-env#8]
hey @mbjoseph  currently it seems like the EA dockerimage here

https://hub.docker.com/r/earthlab/earth-analytics/

only says earth-analytics. it's important this says earth-analytics-python as we have an R course too and i could see making several environments in the future. I dug around this morning and wasn't sure how to make that change however. can you help me understand how do to that?

**Comment by mbjoseph** [comment]
Hi @lwasser - didn't realize you wanted the name to have python in it.

As far as I can tell, we can't rename an automated build. But, we can make a new one with the name you want. Would you like me to do that, or do you want to learn how?

**Comment by lwasser** [comment]
i'd love to see how it works if you don't mind showing me @mbjoseph  i'm learning a lot about docker and it's really great as i'll inevitably get questions from students too. thank you again. i don't mean to be nitpicky. it's just what if we want R in there too? i mean perhaps we might want both? should i consider that? if so then it's ok to have it called earth-analytics .

but that would make it a much larger container to have r and python kernels and associated packages. thoughts?

**Comment by lwasser** [comment]
for giggles. here is data camps r/ notebook integration container

https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile
looks like some julia there too!

im not sure this is exactly what i might want in a combo environment but.. just a starting place

**Comment by mbjoseph** [comment]
@lwasser I would probably avoid having R + Julia + Python together in a Docker image unless it's necessary. That image could get pretty big, which will slow down any automated builds and downloads. 

So, maybe we start with the `earthlab/earth-analytics-python` environment, and then if we need R and/or Julia images we can build those?

**Comment by lwasser** [comment]
perfect. Let's rename it then @mbjoseph i've been calling it -python intentionally knowing i may build out other environments in the future. thank you.

**Comment by lwasser** [comment]
This has been done!!
