### ISSUE TITLE
Change master to main

### ISSUE THREAD

**Issue by nkorinek** [earthlab/earth-analytics-python-env#81]
Need to switch the primary branch of this repo from master to main. I still don't have permissions to do this, but should be easy to do.

**Comment by lwasser** [comment]
you should have permissions now  @nkorinek !!

**Comment by nkorinek** [comment]
I don't see the option still, just fyi

**Comment by lwasser** [comment]
@nkorinek please try again! i gave you full superpowers 🚀

**Comment by nkorinek** [comment]
@lwasser renamed!

**Comment by lwasser** [comment]
great - closing! t hank you!
