### ISSUE TITLE
Instructions for conda environment install should include git install

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/earth-analytics-python-env#9]
It needs to include that git needs to be installed before following the instructions to install the conda environment. Otherwise, the install will fail.

**Comment by lwasser** [comment]
hi @jlpalomino  i'm not sure how i missed this issue coming through. Thank you for posting it. I suggest that you submit a PR to update the readme with the git install instructions! i compltely missed that required step as we all had git already :) thank you. When you submit the pr please link it to this issue.
